steps:
  # Run the Maven build
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t', 'gcr.io/$PROJECT_ID/gcpdockerktl:latest', '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
     - 'CLOUDSDK_CONTAINER_CLUSTER=myk8sclusternew'
     
images: ['gcr.io/$PROJECT_ID/gcpdockerktl:latest']
