apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gcpdockerk8s
  name: gcpdockerk8s
spec:
  replicas: 3
  selector:
    matchLabels:
      run: gcpdockerk8s
  template:
    metadata:
      labels:
        run: gcpdockerk8s
    spec:
      containers:
      - image: gcr.io/$PROJECT_ID/gcpdockerk8s:latest
        name: gcpdockerk8s
        ports:
        - containerPort: 8080